name: ci

on: [push, pull_request]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  deno:
    name: jsonc-morph
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'dsherret:')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: build
        run: deno task build

      - name: fmt
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test
        run: deno test -P

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: npm build
        run: deno task build:npm ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: jsr publish
        run: deno run -A jsr:@david/publish-on-tag@0.2.0
      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm
          npm publish --provenance --access public
